#!/bin/sh
# testing reset back to bkp001 with 1000 backup creation
maxbkp=3
#set -x
mkdir /test/rt
mkdir /test/rt/mnt
mkdir /test/rt/lower
insmod ../../fs/bkpfs/bkpfs.ko
if [ $? -eq 0 ]; then
    echo "Inserted module bkpfs"
else
    echo "Failed to insert module bkpfs"
    exit 1
fi
mount -t bkpfs -o maxver=$maxbkp /test/rt/lower /test/rt/mnt
if [ $? -eq 0 ]; then
    echo Mounted bkpfs with maxver=$maxbkp
else
    echo "Failed to insert module bkpfs"
    exit 1
fi

echo "writing 1000 times to test file..."

echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt
echo "this is not a backup" > /test/rt/mnt/file_$$.txt

echo "running user program to view backups..."
../bkpctl -l /test/rt/mnt/file_$$.txt

echo "testing to see if the backups are correct..."
test -f /test/rt/lower/file_$$.txt.bkp002
if [ $? -eq 0 ]; then
    echo Success! file_$$.txt.bkp002 exists.
else
    echo Fail! file_$$.txt.bkp002 was not created.
fi

test -f /test/rt/lower/file_$$.txt.bkp003
if [ $? -eq 0 ]; then
    echo Success! file_$$.txt.bkp003 exists.
else
    echo Fail! file_$$.txt.bkp003 was not created.
fi

test -f /test/rt/lower/file_$$.txt.bkp004
if [ $? -eq 0 ]; then
    echo Success! file_$$.txt.bkp004 exists.
else
    echo Fail! file_$$.txt.bkp004 was not created.
fi
# Cleanup
umount -t bkpfs /test/rt/lower /test/rt/mnt
rm -rf /test/rt/
rmmod bkpfs


